### ISSUE TITLE
Allow renaming inputs/outputs

### ISSUE THREAD

**Issue by captaincurrie** [geoffreybennett/alsa-scarlett-gui#204]
Hello and thanks for all your hardwork, i use your program every day.

Would be nice to be able to rename everything. Easy to forget that Analogue Outputs 5&6 on my scarlett 4th-gen 4i4 go to my studio monitors. Would be nice to be able to rename them to 'Studio Monitor 1' & 'Studio Monitor 2'

**Comment by geoffreybennett** [comment]
Hi @captaincurrie,

Thanks for your feedback! Please try out the preview of this that I just pushed to the 2464 branch.

Regards,
Geoffrey.

**Comment by unhappy-ending** [comment]
Hello! I'm testing this build now. It's awesome. 

Notes:
PCM Inputs don't seem to change
Levels view doesn't disable the DSP Inputs if they're I/O is disabled
Levels view also doesn't disable for example, channel 9 & 10 if they're altered
Levels view doesn't carry over I/O names.

If it's not planned - no problem!
If it is, I'll assume it will come in time - no problem!

Either way, all good. It's already a huge step up from the previous version.

**Comment by geoffreybennett** [comment]
Hi @captaincurrie, @unhappy-ending,

The 1.0beta branch is now available for testing. Custom port names are in the Configuration window (Ctrl-G), and names propagate throughout the routing, mixer, and DSP windows.

The code is pretty close to what it should be for the 1.0 release, but I still need to test on every supported device, and the docs still need a bunch of work. Feedback welcome!

Custom names, visibility, and linking don't affect the Levels window; I'm not sure how useful that window is now that levels are displayed in the routing and mixer windows, so I left it as basically the raw data, at least for now. LMK if you have thoughts.

Regards,
Geoffrey.

**Comment by captaincurrie** [comment]
Hey @geoffreybennett 

Trying it out now. Seems stable so far. I'm running it on a scarlett 4i4 4th gen and
everything works. I'm getting a 18i16 tomorrow so i'll test it out on that as well
soon.

One thing i dont like is the way you formatted the inputs in the mixer, where they alternate above one another. I know this was done to eliminate potential overlap of names, but its a little jarring. I'll probably get used to it, but i think if the user makes the names small enough that the input names should all be on the same row.

**Comment by geoffreybennett** [comment]
@captaincurrie I was pretty pleased with my alternate-row idea to make the labels fit and was sad to hear you didn't like it 🤣

Please try out 1.0beta4. I came up with an even better idea. Hope you like this one! 🤞

<img width="555" height="249" alt="Image" src="https://github.com/user-attachments/assets/77ef38d9-b97a-4913-87cd-6e70405e369b" />

**Comment by captaincurrie** [comment]
That looks awesome! I tried building 1.0beta4 via the `alsa-scalett-gui-git` pkg in the AUR and i get the following error


    alsa-sim.c: In function ‘sim_card_name’:
    alsa-sim.c:486:16: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
      486 |   char *name = strrchr(fn, '/');
          |                ^~~~~~~
    cc1: all warnings being treated as errors

Also, i've been running the Scarlett 18i16, everything works well, but i've found that sometimes mixer settings are not made persistant. I didnt have this issue with the 4i4. Am i required to save the current mixer state as a configuration so that it can be reloaded on startup? If so how does that system work? Is it the last config saved that gets reloaded automatically?

Also sometimes when i load up the GUI, i get no output from my speakers which is connected to MIX A/B. To solve i unlink and relink the connections and then i have output. Never had this issue with the 4i4. 

Would you like me to open new issues for these and i can try to pinpoint when these issues occur?

**Comment by Marzal** [comment]
I got this error building `1.0beta4` tag or the `1.0beta` branch with [AUR](https://aur.archlinux.org/packages/alsa-scarlett-gui-git)

```
widget-sample-rate.c: In function ‘parse_max_rate’:
widget-sample-rate.c:62:21: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
   62 |   char *rates_str = strstr(line, "Rates: ");
      |                     ^~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:64: widget-sample-rate.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/tmp/makepkg/alsa-scarlett-gui-git/src/alsa-scarlett-gui/src'
==> ERROR: A failure occurred in build().
```

With `1.0beta3` tag I get the same error as captaincurrie
```
alsa-sim.c: En la función ‘sim_card_name’:
alsa-sim.c:486:16: error: la inicialización descarta el calificador ‘const’ del tipo del destino del puntero [-Werror=discarded-qualifiers]
  486 |   char *name = strrchr(fn, '/');
      |                ^~~~~~~
[  7%] CC   device-port-names.c
cc1: todos los avisos se tratan como errores
```

With `1.0beta2` or `1.0beta1` tag same error. A bit strange, I had this working with the `1.0beta` branch a weeks ago.
```
alsa-sim.c: In function ‘sim_card_name’:
alsa-sim.c:486:16: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  486 |   char *name = strrchr(fn, '/');
      |                ^~~~~~~
[  5%] CC   fcp-socket.c
cc1: all warnings being treated as errors
make: *** [Makefile:64: alsa-sim.o] Error 1
```

**Comment by geoffreybennett** [comment]
What version of gcc are you running? I can't reproduce the issue on my Fedora system, so might be a bit of trial and error here. I pushed one more commit to the 1.0beta branch to fix the  issue in `parse_max_rate()` — could you try that please.

**Comment by geoffreybennett** [comment]
Nevermind about the gcc question. I found the issue:

https://sourceware.org/pipermail/libc-alpha/2026-January/174374.html

```
* For ISO C23, the functions bsearch, memchr, strchr, strpbrk, strrchr,
  strstr, wcschr, wcspbrk, wcsrchr, wcsstr and wmemchr that return
  pointers into their input arrays now have definitions as macros that
  return a pointer to a const-qualified type when the input argument is
  a pointer to a const-qualified type.
```

Fedora is still on glibc 2.42. Arch updated to glibc 2.43 recently.

**Comment by Marzal** [comment]
> could you try that please.

Fixed thanks, the [last commit](https://github.com/geoffreybennett/alsa-scarlett-gui/commit/036b3f427c110df3d005a115a474e091dc8e4fd3) of the `beta1.0` branch works.

🥳

**Comment by geoffreybennett** [comment]
@captaincurrie 

> Also sometimes when i load up the GUI, i get no output from my speakers which is connected to MIX A/B. To solve i unlink and relink the connections and then i have output

I have found an issue where after a reboot there is no audio on the Main or Alt outputs until either the main/alt routing is changed or the main/alt switch is toggled.

Can you check the following for me please step by step to confirm if this your problem and let me know what you see:
- In the Routing Window, connect PCM Outputs 1-2 to Hardware Outputs Line 1-2 (the usual/normal thing if you're not doing direct monitoring).
- Play audio, and you should see the Main Window Analogue Output level meters for Line 1-2 and the Routing Window Hardware Outputs Line 1-2 both indicating audio is being played/output (and if your speakers are turned up then you should hear the audio)
- Run `fcp-tool reboot` (leave alsa-scarlett-gui running)
- When your 18i16 returns, I am guessing that you will see the Routing Window indicating audio, but the Main Window NOT indicating audio (and correspondingly you will hear nothing in your speakers) — please confirm that this is your problem.
- In Configuration → Monitor Groups, uncheck Line 1-2 Main Enable
- In Routing, check if anything is connected to Hardware Outputs Line 1-2 and let me know (I am guessing that the answer is no)
- Connect something to Hardware Outputs Line 1-2 (anything, it doesn't matter)
- Recheck Line 1-2 Main Enable
- Retest: play audio, reboot, but this time audio should be present on Line 1-2 in the Main Window (and your speakers) after reboot.

I would call this is a firmware bug, but Focusrite Control 2 doesn't support routing "nothing" to the hardware outputs therefore you can't reproduce this issue with FC2 therefore they're unlikely to fix it. Workaround is as above: disable main/alt in the configuration window, connect something to the output in the routing window, then re-enable main/alt in the configuration window.

As a better workaround, I think I should have alsa-scarlett-gui automatically update the non-main/alt routing behind the scenes to whatever you set main/alt to.

For your other issue with the mixer settings not being persistent, please check that you're not running in to this issue [Why do my settings keep resetting?](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md#why-do-my-settings-keep-resetting). If that's not it, please open a new issue with instructions for me on how to reproduce. All settings should be persistent.

**Comment by captaincurrie** [comment]
Sorry for the delay.
 

> Can you check the following for me please step by step to confirm if this your problem and let me know what you see:
> 
> * In the Routing Window, connect PCM Outputs 1-2 to Hardware Outputs Line 1-2 (the usual/normal thing if you're not doing direct monitoring).
> * Play audio, and you should see the Main Window Analogue Output level meters for Line 1-2 and the Routing Window Hardware Outputs Line 1-2 both indicating audio is being played/output (and if your speakers are turned up then you should hear the audio)
> * Run `fcp-tool reboot` (leave alsa-scarlett-gui running)
> * When your 18i16 returns, I am guessing that you will see the Routing Window indicating audio, but the Main Window NOT indicating audio (and correspondingly you will hear nothing in your speakers) — please confirm that this is your problem.
> * In Configuration → Monitor Groups, uncheck Line 1-2 Main Enable
> * In Routing, check if anything is connected to Hardware Outputs Line 1-2 and let me know (I am guessing that the answer is no)
> * Connect something to Hardware Outputs Line 1-2 (anything, it doesn't matter)
> * Recheck Line 1-2 Main Enable
> * Retest: play audio, reboot, but this time audio should be present on Line 1-2 in the Main Window (and your speakers) after reboot.

Would you like me to perform these steps after a reboot while the issue exists? 

> For your other issue with the mixer settings not being persistent, please check that you're not running in to this issue [Why do my settings keep resetting?](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md#why-do-my-settings-keep-resetting). If that's not it, please open a new issue with instructions for me on how to reproduce. All settings should be persistent.`

This solved the issue, thanks. Settings are now persistant.

Also i complained before about `1.0beta4` not building from AUR, i just successfully built `1.0beta6` after a full system update and am running that now.
